# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1duG_Q-kxxlNd4Kuz2IB-V67X8bCkJdjR
"""

m= {
    "nombre": "javier",
    "matricula": "2416343-6",
    "elded": "16",
    "peso": "75",
    "cel": "3112585858",
    "domicilio": "perukistan",
    "carrera": "cdia",
}
print(m)