# -*- coding: utf-8 -*-
"""neinei.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L9L8RyvBZa6Qe_DIIuFoGSNVzfHsHgqP
"""

def ld():
    e = []
    print("merte la edad de las 10 personas")
    for i in range(10):
        while True:
            entrada = input(f"Ingrese la edad de la persona {i + 1}: ")
            if entrada.isdigit():
                ed = int(entrada)
                e.append(ed)
                break
            else:
                print("acaso aun no naces??")
    return e

def ce(le):
    ma = 0
    me = 0
    EL = 18
    for e in le:
        if e >= EL:
            ma += 1
        else:
            me += 1
    return ma, me

def ir(cm, cme):
    print("\n resultados")
    print(f"las personas son mayores: {cm}")
    print(f"menores de edad: {cme}")

if __name__ == "__main__":
    lde = ld()
    ma, me = ce(lde)
    ir(ma, me)