# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PirBWxRKJpiXbGQKaMV82kAXsJcKGIcS
"""

shopping_list = []

shopping_list = ["Reloj", "Portátil", "Calzado", "Pluma", "Ropa"]

shopping_list.append("Fútbol")

print(shopping_list[0])

print(shopping_list[-1])

print(shopping_list)

print(shopping_list[1])  # Portátil
print(shopping_list[2])  # Calzado

shopping_list[3] = "Cuaderno"
print(shopping_list)

shopping_list.remove("Ropa")
print(shopping_list)

print("Lista final de compras:", shopping_list)