# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1etv6mY30zwI4uyYUYTQABSFo1H2aleI8
"""

tf = [80, 72, 95, 82, 79, 72, 85]
tc = []

for t in tf:
  c = (t - 32) * 5/9
  tc.append(c)

print("fahrenheit")
print(tf)

print("celsius")
print(tc)