# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13HC-zkob3hBkSdoTZYrDFaZ7DVsQOBm1
"""

n = []
s = []
for i in range(5):
    nom = input(f"ingrese el nombre del trabajador {i+1}: ")
    n.append(nom)

    su = float(input(f"ingrese el sueldo de {nom}: $"))
    s.append(su)

nt = sum(s)
sm = max(s)
pm = s.index(sm)
nm = n[pm]

print("\n-Resultados Finales")
print(f"el trabajador con el mayor sueldo es: {nm}")
print(f"la nomina total de la empresa es: ${nt:,.2f}")