# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Xcmm7WX7Ttf85dM_u44ghByr5HDzy-U
"""

def la():
    a = {}
    print("mete los datos de los 10 alumnos")
    for i in range(10):
        n = input(f"nombre del alumnoo {i + 1}: ")
        c = float(input(f"calificacion de {n}: "))
        a[n] = c
    return a

def ins(a):
    print("\nnombres de los alumnos que sacaron mas de  8.5:")
    for n, c in a.items():
        if c > 8.5:
            print(n)

l_a = la()
ins(l_a)